{% set name = "multirtc" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multirtc-{{ version }}.tar.gz
  sha256: a932a6770ddd0d7eeacdc77a8ee0fd1794528c794a78f3ff71d17aaa1fa67560

build:
  entry_points:
    - multirtc = multirtc.multirtc:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - numpy
    - boto3
    - requests
    - lxml
    - shapely
    - pyproj
    - s1reader
    - sarpy
    - burst2safe
    - tqdm
    - hyp3lib

test:
  imports:
    - multirtc
  commands:
    - pip check
    - prep_burst --help
    - multirtc --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Python library for multi-sensor RTC processing using the OPERA algorithm
  home: https://github.com/forrestfwilliams/multirtc
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forrestfwilliams
