{% set name = "multirtc" %}
{% set version = "0.5.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multirtc-{{ version }}.tar.gz
  sha256: c47dff6ead7af43c3b76b61aa1c3c1eaad17a02338e63609b29d335f38056792

build:
  entry_points:
    - multirtc = multirtc.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - numpy
    - boto3
    - requests
    - lxml
    - shapely
    - pyproj
    - s1reader
    - sarpy
    - burst2safe
    - tqdm
    - requests
    - urllib3
    - matplotlib-base
    - pandas
    - lmfit
    - scipy
    - scikit-image
test:
  imports:
    - multirtc
  commands:
    - pip check
    - multirtc --help
    - multirtc rtc --help
    - multirtc geocode --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Python library for multi-sensor RTC processing using the OPERA algorithm
  home: https://github.com/forrestfwilliams/multirtc
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forrestfwilliams
    - Alex-Lewandowski
    - glshort
    - jhkennedy
